name: Fetch FRED Data

on:
  schedule:
    # Runs every day at 05:00 UTC
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # You can specify any version of Node.js that you prefer

    - name: Install dependencies
      run: npm install axios dotenv

    - name: Fetch and save FRED data
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: node fetch_fred_data.js

    - name: Commit and push changes
      run: |
        git config --global user.email "fcjmp@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        git add data/*.csv
        git commit -m "Update FRED data" || exit 0  # Exit 0 if no changes to commit
        git push
